# Generated by Django 3.2.8 on 2021-12-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0002_alter_attendance_total_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Support',
            field=models.CharField(blank=True, choices=[('Offline', 'Offline'), ('Online', 'Online')], max_length=20, null=True),
        ),
    ]
