# Generated by Django 3.2.8 on 2021-12-10 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0003_account_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wrking_Days', models.FloatField(max_length=4, null=True)),
                ('Present_Days', models.FloatField(max_length=4, null=True)),
                ('Holidays', models.FloatField(max_length=4, null=True)),
                ('Leaves', models.FloatField(max_length=4, null=True)),
                ('Leaves_Left', models.FloatField(max_length=4, null=True)),
                ('Absents', models.FloatField(max_length=4, null=True)),
                ('Total_Hours', models.FloatField(max_length=5, null=True)),
                ('Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swpsdata.account')),
            ],
        ),
    ]
