# Generated by Django 3.2.8 on 2021-12-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0005_auto_20211210_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.DateField(help_text='First Date of Required Month and Year (format: yyyy-mm-dd)', unique=True)),
                ('Wrking_Days', models.FloatField(help_text='No of Working Days', max_length=4, null=True)),
                ('Holidays', models.FloatField(help_text='No of Holidays Including Festivals', max_length=4, null=True)),
                ('Extra_Working_Days', models.FloatField(blank=True, help_text='No of Extra Working Days If Any', max_length=4, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Holidays',
        ),
    ]
