# Generated by Django 3.2.8 on 2021-12-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0006_auto_20211210_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthattendance',
            old_name='Wrking_Days',
            new_name='Working_Days',
        ),
        migrations.RemoveField(
            model_name='monthattendance',
            name='Extra_Working_Days',
        ),
        migrations.AddField(
            model_name='monthatnd',
            name='Month',
            field=models.DateField(help_text='First Date of Required Month and Year (format: yyyy-mm-dd)', null=True, unique=True),
        ),
    ]
