# Generated by Django 3.2.8 on 2021-12-10 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0007_auto_20211211_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthatnd',
            old_name='Wrking_Days',
            new_name='Working_Days',
        ),
    ]
