# Generated by Django 3.2.8 on 2021-12-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0008_rename_wrking_days_monthatnd_working_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthatnd',
            name='Month',
            field=models.DateField(help_text='First Date of Required Month and Year (format: yyyy-mm-dd)', null=True),
        ),
    ]
