# Generated by Django 3.2.8 on 2021-12-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0009_alter_monthatnd_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthattendance',
            name='Month',
            field=models.DateField(help_text='Last Date of Required Month and Year (format: yyyy-mm-dd)'),
        ),
    ]
