# Generated by Django 3.2.8 on 2021-12-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0010_alter_monthattendance_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='User_Name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
