# Generated by Django 3.2.8 on 2021-12-17 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0011_account_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthatnd',
            name='Month',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Request_To', models.CharField(max_length=30, null=True)),
                ('Request_For', models.CharField(choices=[('Leave', 'Leave'), ('Permission', 'Permission'), ('OD', 'OD'), ('Tour', 'Tour')], max_length=20)),
                ('Request_Date', models.DateTimeField(auto_now_add=True)),
                ('From_Date', models.DateTimeField(blank=True, null=True)),
                ('To_Date', models.DateTimeField(blank=True, null=True)),
                ('Reason', models.CharField(choices=[('Personal', 'Personal'), ('Casual', 'Casual'), ('Sick', 'Sick'), ('Permission', 'Permission'), ('OD', 'OD'), ('Tour', 'Tour')], max_length=20)),
                ('Acceptance', models.BooleanField(blank=True, default=0)),
                ('Escalate_To', models.CharField(blank=True, max_length=20)),
                ('Request_From', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swpsdata.account')),
            ],
        ),
    ]
