# Generated by Django 3.2.8 on 2021-12-17 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0012_auto_20211217_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='Acceptance',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='Escalate_To',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='Request_From',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swpsdata.account'),
        ),
    ]
