# Generated by Django 3.2.8 on 2021-12-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0014_auto_20211217_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='Acceptance',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='Details',
            field=models.TextField(blank=True, help_text='Add More Work/Visit Details or Add Personal Reasons if interested', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='Status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Not Accepted', 'Not Accepted')], max_length=20, null=True),
        ),
    ]
