# Generated by Django 3.2.8 on 2021-12-17 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0015_auto_20211217_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='Request_From',
            field=models.ForeignKey(limit_choices_to={'Department': 'Management'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='swpsdata.account'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='Request_To',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
