# Generated by Django 3.2.8 on 2021-12-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0020_remove_userrequest_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='Request_Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='From_Date',
            field=models.DateTimeField(null=True),
        ),
    ]
