# Generated by Django 3.2.8 on 2021-12-24 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0021_auto_20211217_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Donor Name', max_length=100, null=True)),
                ('Phone_No', models.IntegerField(blank=True, help_text='Phone Number', null=True)),
                ('Receipt_No', models.CharField(help_text='Receipt Number', max_length=10, null=True, unique=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Gothram', models.CharField(blank=True, help_text='Donor Name', max_length=100, null=True)),
                ('Amount', models.IntegerField(help_text='Amount in Rupees', null=True)),
                ('Paid_Through', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], max_length=20)),
                ('Address', models.TextField(blank=True, help_text='Optional', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonationsCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Donations_Category', models.CharField(blank=True, help_text='Donations Category', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Category', models.CharField(choices=[('Puja Samagri', 'Puja Samagri'), ('Transport', 'Transport'), ('Food', 'Food'), ('General', 'General')], max_length=20)),
                ('Amount', models.FloatField(help_text='Amount in Rupees')),
                ('Towards', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swpsdata.donationscat')),
            ],
        ),
        migrations.CreateModel(
            name='Salaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Amount', models.IntegerField(help_text='Amount in Rupees', null=True)),
                ('Paid_Through', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Staff Name', max_length=100, null=True)),
                ('Phone_No', models.IntegerField(blank=True, help_text='Phone Number', null=True)),
                ('Designation', models.CharField(help_text='Designation of Staff', max_length=50, null=True)),
                ('Address', models.TextField(blank=True, help_text='Address', max_length=1000, null=True)),
                ('Join_Date', models.DateField(blank=True, help_text='Join Date')),
                ('User_Name', models.CharField(help_text='User Name', max_length=20, null=True)),
                ('Is_Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='monthatnd',
            name='Name',
        ),
        migrations.DeleteModel(
            name='MonthAttendance',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='payslips',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='Request_From',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Monthatnd',
        ),
        migrations.DeleteModel(
            name='Movement',
        ),
        migrations.DeleteModel(
            name='Payslips',
        ),
        migrations.DeleteModel(
            name='UserRequest',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
        migrations.AddField(
            model_name='salaries',
            name='Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swpsdata.staff'),
        ),
        migrations.AddField(
            model_name='donations',
            name='Donation_Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swpsdata.donationscat'),
        ),
        migrations.AddField(
            model_name='donations',
            name='Issued_By',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swpsdata.staff'),
        ),
    ]
