# Generated by Django 3.2.8 on 2021-12-24 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0022_auto_20211224_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donations',
            old_name='Name',
            new_name='Donor_Name',
        ),
    ]
