# Generated by Django 3.2.8 on 2021-12-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0023_rename_name_donations_donor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='Date',
            field=models.DateField(),
        ),
    ]
