# Generated by Django 3.2.8 on 2021-12-24 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0027_auto_20211224_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donations',
            old_name='Donation_Category',
            new_name='Donation_Towards',
        ),
    ]
