# Generated by Django 3.2.8 on 2021-12-24 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0028_rename_donation_category_donations_donation_towards'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='By',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swpsdata.staff'),
        ),
    ]
