# Generated by Django 3.2.8 on 2021-12-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0031_alter_staff_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='Date',
            field=models.DateField(),
        ),
    ]
