# Generated by Django 3.2.8 on 2021-12-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0033_expenses_paid_through'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='Category',
            field=models.CharField(choices=[('Puja Samagri', 'Puja Samagri'), ('Transport', 'Transport'), ('Food', 'Food'), ('Salary', 'Salary'), ('General', 'General')], max_length=20),
        ),
    ]
