# Generated by Django 3.2.8 on 2021-12-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0034_auto_20211227_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
