# Generated by Django 3.2.8 on 2021-12-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0035_alter_donations_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
