# Generated by Django 3.2.8 on 2021-12-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0037_auto_20211227_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
