# Generated by Django 3.2.8 on 2021-12-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0040_auto_20211228_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
