# Generated by Django 2.2.1 on 2021-12-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0041_alter_donations_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='Status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Due', 'Due')], max_length=20, null=True),
        ),
    ]
