# Generated by Django 2.2.1 on 2021-12-29 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0042_donations_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='Issued_By',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='swpsdata.Staff'),
        ),
    ]
