# Generated by Django 2.2.1 on 2021-12-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0044_auto_20211229_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='Issued_By',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
