# Generated by Django 3.2.8 on 2022-01-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0046_auto_20211229_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hundi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(help_text='Enter any Date within the hundi collection month')),
                ('Amount', models.IntegerField(help_text='Amount in Rupees', null=True)),
                ('Issued_By', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
