# Generated by Django 3.2.8 on 2022-01-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0047_hundi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hundi',
            name='Issued_By',
        ),
        migrations.AddField(
            model_name='hundi',
            name='By',
            field=models.CharField(blank=True, help_text='Collected/Handover To', max_length=30, null=True),
        ),
    ]
