# Generated by Django 3.2.8 on 2022-01-03 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0048_auto_20220103_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hundi',
            name='By',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swpsdata.staff'),
        ),
    ]
